// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	inference "github.com/wambozi/sigil/internal/inference"
)

// MockBackend is an autogenerated mock type for the Backend type
type MockBackend struct {
	mock.Mock
}

// Complete provides a mock function with given fields: ctx, system, user
func (_m *MockBackend) Complete(ctx context.Context, system string, user string) (*inference.CompletionResult, error) {
	ret := _m.Called(ctx, system, user)

	if len(ret) == 0 {
		panic("no return value specified for Complete")
	}

	var r0 *inference.CompletionResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*inference.CompletionResult, error)); ok {
		return rf(ctx, system, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *inference.CompletionResult); ok {
		r0 = rf(ctx, system, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*inference.CompletionResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, system, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Ping provides a mock function with given fields: ctx
func (_m *MockBackend) Ping(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockBackend creates a new instance of MockBackend. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBackend(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBackend {
	mock := &MockBackend{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
