// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcceptSuggestion(arg1:number):Promise<void>;

export function Ask(arg1:string):Promise<Record<string, any>>;

export function DisablePlugin(arg1:string):Promise<void>;

export function DismissSuggestion(arg1:number):Promise<void>;

export function EnablePlugin(arg1:string):Promise<void>;

export function GetConfig():Promise<Record<string, any>>;

export function GetCurrentTask():Promise<Record<string, any>>;

export function GetDaySummary():Promise<Record<string, any>>;

export function GetPluginRegistry():Promise<Array<Record<string, any>>>;

export function GetPluginStatus():Promise<Array<Record<string, any>>>;

export function GetStatus():Promise<Record<string, any>>;

export function GetSuggestions():Promise<Array<Record<string, any>>>;

export function InstallPlugin(arg1:string):Promise<void>;

export function IsConnected():Promise<boolean>;

export function RestartDaemon():Promise<void>;

export function SetConfig(arg1:Record<string, any>):Promise<Record<string, any>>;

export function SetLevel(arg1:number):Promise<void>;

export function StartDaemon():Promise<void>;

export function StopDaemon():Promise<void>;
