// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcceptSuggestion(arg1) {
  return window['go']['main']['App']['AcceptSuggestion'](arg1);
}

export function Ask(arg1) {
  return window['go']['main']['App']['Ask'](arg1);
}

export function DisablePlugin(arg1) {
  return window['go']['main']['App']['DisablePlugin'](arg1);
}

export function DismissSuggestion(arg1) {
  return window['go']['main']['App']['DismissSuggestion'](arg1);
}

export function EnablePlugin(arg1) {
  return window['go']['main']['App']['EnablePlugin'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetCurrentTask() {
  return window['go']['main']['App']['GetCurrentTask']();
}

export function GetDaySummary() {
  return window['go']['main']['App']['GetDaySummary']();
}

export function GetPluginRegistry() {
  return window['go']['main']['App']['GetPluginRegistry']();
}

export function GetPluginStatus() {
  return window['go']['main']['App']['GetPluginStatus']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetSuggestions() {
  return window['go']['main']['App']['GetSuggestions']();
}

export function InstallPlugin(arg1) {
  return window['go']['main']['App']['InstallPlugin'](arg1);
}

export function IsConnected() {
  return window['go']['main']['App']['IsConnected']();
}

export function RestartDaemon() {
  return window['go']['main']['App']['RestartDaemon']();
}

export function SetConfig(arg1) {
  return window['go']['main']['App']['SetConfig'](arg1);
}

export function SetLevel(arg1) {
  return window['go']['main']['App']['SetLevel'](arg1);
}

export function StartDaemon() {
  return window['go']['main']['App']['StartDaemon']();
}

export function StopDaemon() {
  return window['go']['main']['App']['StopDaemon']();
}
