apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
stringData:
  FLEET_API_KEY: {{ .Values.secrets.apiKey | quote }}
  {{- if .Values.secrets.oidcClientSecret }}
  FLEET_OIDC_CLIENT_SECRET: {{ .Values.secrets.oidcClientSecret | quote }}
  {{- end }}
