// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	event "github.com/wambozi/sigil/internal/event"

	store "github.com/wambozi/sigil/internal/store"

	time "time"
)

// MockReadWriter is an autogenerated mock type for the ReadWriter type
type MockReadWriter struct {
	mock.Mock
}

// CountEvents provides a mock function with given fields: ctx, kind, since
func (_m *MockReadWriter) CountEvents(ctx context.Context, kind event.Kind, since time.Time) (int64, error) {
	ret := _m.Called(ctx, kind, since)

	if len(ret) == 0 {
		panic("no return value specified for CountEvents")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, event.Kind, time.Time) (int64, error)); ok {
		return rf(ctx, kind, since)
	}
	if rf, ok := ret.Get(0).(func(context.Context, event.Kind, time.Time) int64); ok {
		r0 = rf(ctx, kind, since)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, event.Kind, time.Time) error); ok {
		r1 = rf(ctx, kind, since)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertAIInteraction provides a mock function with given fields: ctx, ai
func (_m *MockReadWriter) InsertAIInteraction(ctx context.Context, ai event.AIInteraction) error {
	ret := _m.Called(ctx, ai)

	if len(ret) == 0 {
		panic("no return value specified for InsertAIInteraction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, event.AIInteraction) error); ok {
		r0 = rf(ctx, ai)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InsertAction provides a mock function with given fields: ctx, actionID, description, executeCmd, undoCmd, createdAt, expiresAt
func (_m *MockReadWriter) InsertAction(ctx context.Context, actionID string, description string, executeCmd string, undoCmd string, createdAt time.Time, expiresAt time.Time) error {
	ret := _m.Called(ctx, actionID, description, executeCmd, undoCmd, createdAt, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for InsertAction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, time.Time, time.Time) error); ok {
		r0 = rf(ctx, actionID, description, executeCmd, undoCmd, createdAt, expiresAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InsertEvent provides a mock function with given fields: ctx, e
func (_m *MockReadWriter) InsertEvent(ctx context.Context, e event.Event) error {
	ret := _m.Called(ctx, e)

	if len(ret) == 0 {
		panic("no return value specified for InsertEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, event.Event) error); ok {
		r0 = rf(ctx, e)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InsertFeedback provides a mock function with given fields: ctx, suggestionID, outcome
func (_m *MockReadWriter) InsertFeedback(ctx context.Context, suggestionID int64, outcome string) error {
	ret := _m.Called(ctx, suggestionID, outcome)

	if len(ret) == 0 {
		panic("no return value specified for InsertFeedback")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) error); ok {
		r0 = rf(ctx, suggestionID, outcome)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InsertPattern provides a mock function with given fields: ctx, kind, summary
func (_m *MockReadWriter) InsertPattern(ctx context.Context, kind string, summary interface{}) error {
	ret := _m.Called(ctx, kind, summary)

	if len(ret) == 0 {
		panic("no return value specified for InsertPattern")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}) error); ok {
		r0 = rf(ctx, kind, summary)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InsertSuggestion provides a mock function with given fields: ctx, sg
func (_m *MockReadWriter) InsertSuggestion(ctx context.Context, sg store.Suggestion) (int64, error) {
	ret := _m.Called(ctx, sg)

	if len(ret) == 0 {
		panic("no return value specified for InsertSuggestion")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, store.Suggestion) (int64, error)); ok {
		return rf(ctx, sg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, store.Suggestion) int64); ok {
		r0 = rf(ctx, sg)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, store.Suggestion) error); ok {
		r1 = rf(ctx, sg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarkActionUndone provides a mock function with given fields: ctx, actionID
func (_m *MockReadWriter) MarkActionUndone(ctx context.Context, actionID string) error {
	ret := _m.Called(ctx, actionID)

	if len(ret) == 0 {
		panic("no return value specified for MarkActionUndone")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, actionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// QueryAIInteractions provides a mock function with given fields: ctx, since
func (_m *MockReadWriter) QueryAIInteractions(ctx context.Context, since time.Time) ([]event.AIInteraction, error) {
	ret := _m.Called(ctx, since)

	if len(ret) == 0 {
		panic("no return value specified for QueryAIInteractions")
	}

	var r0 []event.AIInteraction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) ([]event.AIInteraction, error)); ok {
		return rf(ctx, since)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) []event.AIInteraction); ok {
		r0 = rf(ctx, since)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]event.AIInteraction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, since)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// QueryEvents provides a mock function with given fields: ctx, kind, n
func (_m *MockReadWriter) QueryEvents(ctx context.Context, kind event.Kind, n int) ([]event.Event, error) {
	ret := _m.Called(ctx, kind, n)

	if len(ret) == 0 {
		panic("no return value specified for QueryEvents")
	}

	var r0 []event.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, event.Kind, int) ([]event.Event, error)); ok {
		return rf(ctx, kind, n)
	}
	if rf, ok := ret.Get(0).(func(context.Context, event.Kind, int) []event.Event); ok {
		r0 = rf(ctx, kind, n)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]event.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, event.Kind, int) error); ok {
		r1 = rf(ctx, kind, n)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// QueryHyprlandEvents provides a mock function with given fields: ctx, since
func (_m *MockReadWriter) QueryHyprlandEvents(ctx context.Context, since time.Time) ([]event.Event, error) {
	ret := _m.Called(ctx, since)

	if len(ret) == 0 {
		panic("no return value specified for QueryHyprlandEvents")
	}

	var r0 []event.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) ([]event.Event, error)); ok {
		return rf(ctx, since)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) []event.Event); ok {
		r0 = rf(ctx, since)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]event.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, since)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// QueryPattern provides a mock function with given fields: ctx, kind, dest
func (_m *MockReadWriter) QueryPattern(ctx context.Context, kind string, dest interface{}) error {
	ret := _m.Called(ctx, kind, dest)

	if len(ret) == 0 {
		panic("no return value specified for QueryPattern")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}) error); ok {
		r0 = rf(ctx, kind, dest)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// QueryRecentFileEvents provides a mock function with given fields: ctx, since
func (_m *MockReadWriter) QueryRecentFileEvents(ctx context.Context, since time.Time) ([]event.Event, error) {
	ret := _m.Called(ctx, since)

	if len(ret) == 0 {
		panic("no return value specified for QueryRecentFileEvents")
	}

	var r0 []event.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) ([]event.Event, error)); ok {
		return rf(ctx, since)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) []event.Event); ok {
		r0 = rf(ctx, since)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]event.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, since)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// QueryResolvedSuggestionCount provides a mock function with given fields: ctx, since
func (_m *MockReadWriter) QueryResolvedSuggestionCount(ctx context.Context, since time.Time) (int64, error) {
	ret := _m.Called(ctx, since)

	if len(ret) == 0 {
		panic("no return value specified for QueryResolvedSuggestionCount")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) (int64, error)); ok {
		return rf(ctx, since)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) int64); ok {
		r0 = rf(ctx, since)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, since)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// QuerySuggestionAcceptanceRate provides a mock function with given fields: ctx, since
func (_m *MockReadWriter) QuerySuggestionAcceptanceRate(ctx context.Context, since time.Time) (float64, error) {
	ret := _m.Called(ctx, since)

	if len(ret) == 0 {
		panic("no return value specified for QuerySuggestionAcceptanceRate")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) (float64, error)); ok {
		return rf(ctx, since)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) float64); ok {
		r0 = rf(ctx, since)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, since)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// QuerySuggestions provides a mock function with given fields: ctx, status, n
func (_m *MockReadWriter) QuerySuggestions(ctx context.Context, status store.SuggestionStatus, n int) ([]store.Suggestion, error) {
	ret := _m.Called(ctx, status, n)

	if len(ret) == 0 {
		panic("no return value specified for QuerySuggestions")
	}

	var r0 []store.Suggestion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, store.SuggestionStatus, int) ([]store.Suggestion, error)); ok {
		return rf(ctx, status, n)
	}
	if rf, ok := ret.Get(0).(func(context.Context, store.SuggestionStatus, int) []store.Suggestion); ok {
		r0 = rf(ctx, status, n)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]store.Suggestion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, store.SuggestionStatus, int) error); ok {
		r1 = rf(ctx, status, n)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// QueryTerminalEvents provides a mock function with given fields: ctx, since
func (_m *MockReadWriter) QueryTerminalEvents(ctx context.Context, since time.Time) ([]event.Event, error) {
	ret := _m.Called(ctx, since)

	if len(ret) == 0 {
		panic("no return value specified for QueryTerminalEvents")
	}

	var r0 []event.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) ([]event.Event, error)); ok {
		return rf(ctx, since)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) []event.Event); ok {
		r0 = rf(ctx, since)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]event.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, since)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// QueryTopFiles provides a mock function with given fields: ctx, since, n
func (_m *MockReadWriter) QueryTopFiles(ctx context.Context, since time.Time, n int) ([]store.FileEditCount, error) {
	ret := _m.Called(ctx, since, n)

	if len(ret) == 0 {
		panic("no return value specified for QueryTopFiles")
	}

	var r0 []store.FileEditCount
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, int) ([]store.FileEditCount, error)); ok {
		return rf(ctx, since, n)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, int) []store.FileEditCount); ok {
		r0 = rf(ctx, since, n)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]store.FileEditCount)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time, int) error); ok {
		r1 = rf(ctx, since, n)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// QueryUndoableActions provides a mock function with given fields: ctx
func (_m *MockReadWriter) QueryUndoableActions(ctx context.Context) ([]store.ActionRecord, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for QueryUndoableActions")
	}

	var r0 []store.ActionRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]store.ActionRecord, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []store.ActionRecord); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]store.ActionRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateSuggestionStatus provides a mock function with given fields: ctx, id, status
func (_m *MockReadWriter) UpdateSuggestionStatus(ctx context.Context, id int64, status store.SuggestionStatus) error {
	ret := _m.Called(ctx, id, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSuggestionStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, store.SuggestionStatus) error); ok {
		r0 = rf(ctx, id, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockReadWriter creates a new instance of MockReadWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReadWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReadWriter {
	mock := &MockReadWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
