// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	event "github.com/wambozi/sigil/internal/event"

	store "github.com/wambozi/sigil/internal/store"

	time "time"
)

// MockEventWriter is an autogenerated mock type for the EventWriter type
type MockEventWriter struct {
	mock.Mock
}

// InsertAIInteraction provides a mock function with given fields: ctx, ai
func (_m *MockEventWriter) InsertAIInteraction(ctx context.Context, ai event.AIInteraction) error {
	ret := _m.Called(ctx, ai)

	if len(ret) == 0 {
		panic("no return value specified for InsertAIInteraction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, event.AIInteraction) error); ok {
		r0 = rf(ctx, ai)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InsertAction provides a mock function with given fields: ctx, actionID, description, executeCmd, undoCmd, createdAt, expiresAt
func (_m *MockEventWriter) InsertAction(ctx context.Context, actionID string, description string, executeCmd string, undoCmd string, createdAt time.Time, expiresAt time.Time) error {
	ret := _m.Called(ctx, actionID, description, executeCmd, undoCmd, createdAt, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for InsertAction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, time.Time, time.Time) error); ok {
		r0 = rf(ctx, actionID, description, executeCmd, undoCmd, createdAt, expiresAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InsertEvent provides a mock function with given fields: ctx, e
func (_m *MockEventWriter) InsertEvent(ctx context.Context, e event.Event) error {
	ret := _m.Called(ctx, e)

	if len(ret) == 0 {
		panic("no return value specified for InsertEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, event.Event) error); ok {
		r0 = rf(ctx, e)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InsertFeedback provides a mock function with given fields: ctx, suggestionID, outcome
func (_m *MockEventWriter) InsertFeedback(ctx context.Context, suggestionID int64, outcome string) error {
	ret := _m.Called(ctx, suggestionID, outcome)

	if len(ret) == 0 {
		panic("no return value specified for InsertFeedback")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) error); ok {
		r0 = rf(ctx, suggestionID, outcome)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InsertMLEvent provides a mock function with given fields: ctx, kind, endpoint, routing, latencyMS
func (_m *MockEventWriter) InsertMLEvent(ctx context.Context, kind string, endpoint string, routing string, latencyMS int64) error {
	ret := _m.Called(ctx, kind, endpoint, routing, latencyMS)

	if len(ret) == 0 {
		panic("no return value specified for InsertMLEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, int64) error); ok {
		r0 = rf(ctx, kind, endpoint, routing, latencyMS)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InsertPattern provides a mock function with given fields: ctx, kind, summary
func (_m *MockEventWriter) InsertPattern(ctx context.Context, kind string, summary interface{}) error {
	ret := _m.Called(ctx, kind, summary)

	if len(ret) == 0 {
		panic("no return value specified for InsertPattern")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}) error); ok {
		r0 = rf(ctx, kind, summary)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InsertSuggestion provides a mock function with given fields: ctx, sg
func (_m *MockEventWriter) InsertSuggestion(ctx context.Context, sg store.Suggestion) (int64, error) {
	ret := _m.Called(ctx, sg)

	if len(ret) == 0 {
		panic("no return value specified for InsertSuggestion")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, store.Suggestion) (int64, error)); ok {
		return rf(ctx, sg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, store.Suggestion) int64); ok {
		r0 = rf(ctx, sg)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, store.Suggestion) error); ok {
		r1 = rf(ctx, sg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertTask provides a mock function with given fields: ctx, t
func (_m *MockEventWriter) InsertTask(ctx context.Context, t store.TaskRecord) error {
	ret := _m.Called(ctx, t)

	if len(ret) == 0 {
		panic("no return value specified for InsertTask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, store.TaskRecord) error); ok {
		r0 = rf(ctx, t)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MarkActionUndone provides a mock function with given fields: ctx, actionID
func (_m *MockEventWriter) MarkActionUndone(ctx context.Context, actionID string) error {
	ret := _m.Called(ctx, actionID)

	if len(ret) == 0 {
		panic("no return value specified for MarkActionUndone")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, actionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateSuggestionStatus provides a mock function with given fields: ctx, id, status
func (_m *MockEventWriter) UpdateSuggestionStatus(ctx context.Context, id int64, status store.SuggestionStatus) error {
	ret := _m.Called(ctx, id, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSuggestionStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, store.SuggestionStatus) error); ok {
		r0 = rf(ctx, id, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateTask provides a mock function with given fields: ctx, t
func (_m *MockEventWriter) UpdateTask(ctx context.Context, t store.TaskRecord) error {
	ret := _m.Called(ctx, t)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, store.TaskRecord) error); ok {
		r0 = rf(ctx, t)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InsertPrediction provides a mock function with given fields: ctx, model, result, confidence, expiresAt
func (_m *MockEventWriter) InsertPrediction(ctx context.Context, model string, result string, confidence float64, expiresAt *time.Time) error {
	ret := _m.Called(ctx, model, result, confidence, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for InsertPrediction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, float64, *time.Time) error); ok {
		r0 = rf(ctx, model, result, confidence, expiresAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockEventWriter creates a new instance of MockEventWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventWriter {
	mock := &MockEventWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
