// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	event "github.com/wambozi/sigil/internal/event"

	store "github.com/wambozi/sigil/internal/store"

	time "time"
)

// MockEventReader is an autogenerated mock type for the EventReader type
type MockEventReader struct {
	mock.Mock
}

// CountEvents provides a mock function with given fields: ctx, kind, since
func (_m *MockEventReader) CountEvents(ctx context.Context, kind event.Kind, since time.Time) (int64, error) {
	ret := _m.Called(ctx, kind, since)

	if len(ret) == 0 {
		panic("no return value specified for CountEvents")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, event.Kind, time.Time) (int64, error)); ok {
		return rf(ctx, kind, since)
	}
	if rf, ok := ret.Get(0).(func(context.Context, event.Kind, time.Time) int64); ok {
		r0 = rf(ctx, kind, since)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, event.Kind, time.Time) error); ok {
		r1 = rf(ctx, kind, since)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// QueryAIInteractions provides a mock function with given fields: ctx, since
func (_m *MockEventReader) QueryAIInteractions(ctx context.Context, since time.Time) ([]event.AIInteraction, error) {
	ret := _m.Called(ctx, since)

	if len(ret) == 0 {
		panic("no return value specified for QueryAIInteractions")
	}

	var r0 []event.AIInteraction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) ([]event.AIInteraction, error)); ok {
		return rf(ctx, since)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) []event.AIInteraction); ok {
		r0 = rf(ctx, since)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]event.AIInteraction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, since)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// QueryEvents provides a mock function with given fields: ctx, kind, n
func (_m *MockEventReader) QueryEvents(ctx context.Context, kind event.Kind, n int) ([]event.Event, error) {
	ret := _m.Called(ctx, kind, n)

	if len(ret) == 0 {
		panic("no return value specified for QueryEvents")
	}

	var r0 []event.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, event.Kind, int) ([]event.Event, error)); ok {
		return rf(ctx, kind, n)
	}
	if rf, ok := ret.Get(0).(func(context.Context, event.Kind, int) []event.Event); ok {
		r0 = rf(ctx, kind, n)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]event.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, event.Kind, int) error); ok {
		r1 = rf(ctx, kind, n)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// QueryHyprlandEvents provides a mock function with given fields: ctx, since
func (_m *MockEventReader) QueryHyprlandEvents(ctx context.Context, since time.Time) ([]event.Event, error) {
	ret := _m.Called(ctx, since)

	if len(ret) == 0 {
		panic("no return value specified for QueryHyprlandEvents")
	}

	var r0 []event.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) ([]event.Event, error)); ok {
		return rf(ctx, since)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) []event.Event); ok {
		r0 = rf(ctx, since)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]event.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, since)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// QueryPattern provides a mock function with given fields: ctx, kind, dest
func (_m *MockEventReader) QueryPattern(ctx context.Context, kind string, dest interface{}) error {
	ret := _m.Called(ctx, kind, dest)

	if len(ret) == 0 {
		panic("no return value specified for QueryPattern")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}) error); ok {
		r0 = rf(ctx, kind, dest)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// QueryRecentFileEvents provides a mock function with given fields: ctx, since
func (_m *MockEventReader) QueryRecentFileEvents(ctx context.Context, since time.Time) ([]event.Event, error) {
	ret := _m.Called(ctx, since)

	if len(ret) == 0 {
		panic("no return value specified for QueryRecentFileEvents")
	}

	var r0 []event.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) ([]event.Event, error)); ok {
		return rf(ctx, since)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) []event.Event); ok {
		r0 = rf(ctx, since)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]event.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, since)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// QueryResolvedSuggestionCount provides a mock function with given fields: ctx, since
func (_m *MockEventReader) QueryResolvedSuggestionCount(ctx context.Context, since time.Time) (int64, error) {
	ret := _m.Called(ctx, since)

	if len(ret) == 0 {
		panic("no return value specified for QueryResolvedSuggestionCount")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) (int64, error)); ok {
		return rf(ctx, since)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) int64); ok {
		r0 = rf(ctx, since)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, since)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// QuerySuggestionAcceptanceRate provides a mock function with given fields: ctx, since
func (_m *MockEventReader) QuerySuggestionAcceptanceRate(ctx context.Context, since time.Time) (float64, error) {
	ret := _m.Called(ctx, since)

	if len(ret) == 0 {
		panic("no return value specified for QuerySuggestionAcceptanceRate")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) (float64, error)); ok {
		return rf(ctx, since)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) float64); ok {
		r0 = rf(ctx, since)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, since)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// QuerySuggestions provides a mock function with given fields: ctx, status, n
func (_m *MockEventReader) QuerySuggestions(ctx context.Context, status store.SuggestionStatus, n int) ([]store.Suggestion, error) {
	ret := _m.Called(ctx, status, n)

	if len(ret) == 0 {
		panic("no return value specified for QuerySuggestions")
	}

	var r0 []store.Suggestion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, store.SuggestionStatus, int) ([]store.Suggestion, error)); ok {
		return rf(ctx, status, n)
	}
	if rf, ok := ret.Get(0).(func(context.Context, store.SuggestionStatus, int) []store.Suggestion); ok {
		r0 = rf(ctx, status, n)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]store.Suggestion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, store.SuggestionStatus, int) error); ok {
		r1 = rf(ctx, status, n)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// QueryTerminalEvents provides a mock function with given fields: ctx, since
func (_m *MockEventReader) QueryTerminalEvents(ctx context.Context, since time.Time) ([]event.Event, error) {
	ret := _m.Called(ctx, since)

	if len(ret) == 0 {
		panic("no return value specified for QueryTerminalEvents")
	}

	var r0 []event.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) ([]event.Event, error)); ok {
		return rf(ctx, since)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) []event.Event); ok {
		r0 = rf(ctx, since)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]event.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, since)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// QueryTopFiles provides a mock function with given fields: ctx, since, n
func (_m *MockEventReader) QueryTopFiles(ctx context.Context, since time.Time, n int) ([]store.FileEditCount, error) {
	ret := _m.Called(ctx, since, n)

	if len(ret) == 0 {
		panic("no return value specified for QueryTopFiles")
	}

	var r0 []store.FileEditCount
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, int) ([]store.FileEditCount, error)); ok {
		return rf(ctx, since, n)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, int) []store.FileEditCount); ok {
		r0 = rf(ctx, since, n)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]store.FileEditCount)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time, int) error); ok {
		r1 = rf(ctx, since, n)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// QueryUndoableActions provides a mock function with given fields: ctx
func (_m *MockEventReader) QueryUndoableActions(ctx context.Context) ([]store.ActionRecord, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for QueryUndoableActions")
	}

	var r0 []store.ActionRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]store.ActionRecord, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []store.ActionRecord); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]store.ActionRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockEventReader creates a new instance of MockEventReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventReader {
	mock := &MockEventReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
