// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockPlatform is an autogenerated mock type for the Platform type
type MockPlatform struct {
	mock.Mock
}

// Execute provides a mock function with given fields: cmd
func (_m *MockPlatform) Execute(cmd string) error {
	ret := _m.Called(cmd)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Send provides a mock function with given fields: title, body, withAction
func (_m *MockPlatform) Send(title string, body string, withAction bool) {
	_m.Called(title, body, withAction)
}

// NewMockPlatform creates a new instance of MockPlatform. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPlatform(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPlatform {
	mock := &MockPlatform{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
