package main

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/wambozi/sigil/internal/config"
	"github.com/wambozi/sigil/internal/socket"
)

// registerInitHandlers adds the check-init and init socket methods.
func registerInitHandlers(srv *socket.Server) {
	// check-init — returns whether a config.toml exists.
	srv.Handle("check-init", func(_ context.Context, _ socket.Request) socket.Response {
		cfgPath := config.DefaultPath()
		_, err := os.Stat(cfgPath)
		initialized := err == nil

		payload, _ := json.Marshal(map[string]any{
			"initialized": initialized,
			"config_path": cfgPath,
		})
		return socket.Response{OK: true, Payload: payload}
	})

	// init — accepts a config payload from the wizard and writes config.toml.
	srv.Handle("init", func(_ context.Context, req socket.Request) socket.Response {
		var p initPayload
		if err := json.Unmarshal(req.Payload, &p); err != nil {
			return socket.Response{Error: "invalid payload: " + err.Error()}
		}

		if err := writeInitConfig(p); err != nil {
			return socket.Response{Error: err.Error()}
		}

		payload, _ := json.Marshal(map[string]any{"ok": true})
		return socket.Response{OK: true, Payload: payload}
	})
}

// initPayload is the config sent by both the onboarding wizard and sigild init.
// Both code paths build this struct and call writeInitConfig.
type initPayload struct {
	WatchDirs         []string `json:"watch_dirs"`
	RepoDirs          []string `json:"repo_dirs"`
	InferenceMode     string   `json:"inference_mode"`
	NotificationLevel int      `json:"notification_level"`
	Plugins           []string `json:"plugins"`
	CloudEnabled      bool     `json:"cloud_enabled"`
	CloudProvider     string   `json:"cloud_provider"`
	CloudAPIKey       string   `json:"cloud_api_key"`
	LocalInference    bool     `json:"local_inference"`
	FleetEnabled      bool     `json:"fleet_enabled"`
	FleetEndpoint     string   `json:"fleet_endpoint"`
	MLEnabled         bool     `json:"ml_enabled"`
	MLMode            string   `json:"ml_mode"`
}

// writeInitConfig creates config.toml from the wizard payload.
// This is the shared config-writing logic used by both the socket handler
// and the CLI init subcommand.
func writeInitConfig(p initPayload) error {
	cfgPath := config.DefaultPath()

	if err := os.MkdirAll(filepath.Dir(cfgPath), 0o700); err != nil {
		return fmt.Errorf("create config dir: %w", err)
	}

	// Determine watch dirs (default to ~/code or first common dir).
	watchDirs := p.WatchDirs
	if len(watchDirs) == 0 {
		home, _ := os.UserHomeDir()
		watchDirs = []string{defaultWatchDir(home)}
	}

	// Determine inference mode.
	mode := p.InferenceMode
	if mode == "" {
		switch {
		case p.LocalInference && p.CloudEnabled:
			mode = "localfirst"
		case p.LocalInference:
			mode = "local"
		case p.CloudEnabled:
			mode = "remote"
		default:
			mode = "localfirst"
		}
	}

	var b strings.Builder
	b.WriteString("# Sigil daemon configuration\n# Generated by Sigil setup wizard\n\n")
	b.WriteString("[daemon]\nlog_level = \"info\"\n")

	// Watch dirs
	b.WriteString("watch_dirs = [")
	if len(watchDirs) == 1 {
		fmt.Fprintf(&b, "%q", watchDirs[0])
	} else {
		b.WriteString("\n")
		for _, d := range watchDirs {
			fmt.Fprintf(&b, "  %q,\n", d)
		}
	}
	b.WriteString("]\n")

	// Repo dirs (discovered by CLI, empty from wizard).
	if len(p.RepoDirs) > 0 {
		b.WriteString("repo_dirs = [\n")
		for _, d := range p.RepoDirs {
			fmt.Fprintf(&b, "  %q,\n", d)
		}
		b.WriteString("]\n")
	}

	// Notifier
	level := p.NotificationLevel
	if level < 0 || level > 4 {
		level = 2
	}
	fmt.Fprintf(&b, "\n[notifier]\nlevel = %d\ndigest_time = \"09:00\"\n", level)

	// Inference
	fmt.Fprintf(&b, "\n[inference]\nmode = %q\n", mode)
	fmt.Fprintf(&b, "\n[inference.local]\nenabled = %t\n", p.LocalInference)
	fmt.Fprintf(&b, "\n[inference.cloud]\nenabled = %t\n", p.CloudEnabled)
	if p.CloudEnabled && p.CloudProvider != "" {
		fmt.Fprintf(&b, "provider = %q\n", p.CloudProvider)
	}
	if p.CloudEnabled && p.CloudAPIKey != "" {
		fmt.Fprintf(&b, "api_key = %q\n", p.CloudAPIKey)
	}

	// ML
	mlMode := p.MLMode
	if mlMode == "" {
		if p.MLEnabled {
			mlMode = "local"
		} else {
			mlMode = "disabled"
		}
	}
	fmt.Fprintf(&b, "\n[ml]\nmode = %q\n", mlMode)
	if p.MLEnabled {
		b.WriteString("\n[ml.local]\nenabled = true\nserver_url = \"http://127.0.0.1:7774\"\n")
	}

	// Retention
	b.WriteString("\n[retention]\nraw_event_days = 90\n")

	// Fleet
	fmt.Fprintf(&b, "\n[fleet]\nenabled = %t\n", p.FleetEnabled)
	if p.FleetEnabled {
		endpoint := p.FleetEndpoint
		if endpoint == "" {
			endpoint = config.DefaultFleetEndpoint
		}
		fmt.Fprintf(&b, "endpoint = %q\n", endpoint)
	}
	b.WriteString("\n")

	return os.WriteFile(cfgPath, []byte(b.String()), 0o600)
}

// defaultWatchDir returns the first existing common code directory or ~/code.
func defaultWatchDir(home string) string {
	for _, candidate := range []string{"code", "projects", "src", "workspace", "dev"} {
		p := filepath.Join(home, candidate)
		if info, err := os.Stat(p); err == nil && info.IsDir() {
			return "~/" + candidate
		}
	}
	return "~/code"
}
